version: '3.8'

services:
  # ====================================
  # Autocoin Spring API Application
  # ====================================
  autocoin-api:
    image: ghcr.io/autocoinproject/autocoin-api:latest
    container_name: autocoin-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Application
      - SPRING_PROFILES_ACTIVE=prod
      
      # Database
      - DB_HOST=${DB_HOST:-autocoin-rds.cz7dv3rknd8e.ap-northeast-2.rds.amazonaws.com}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-autocoin}
      - DB_USERNAME=${DB_USERNAME:-admin}
      - DB_PASSWORD=${DB_PASSWORD}
      
      # Security
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-1800000}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-604800000}
      
      # External APIs
      - UPBIT_ENCRYPTION_KEY=${UPBIT_ENCRYPTION_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
      
      # AWS
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET:-autocoin-s3-bucket}
      - AWS_REGION=${AWS_REGION:-ap-northeast-2}
      
      # Monitoring
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SLACK_NOTIFICATIONS_ENABLED=${SLACK_NOTIFICATIONS_ENABLED:-true}
      - SENTRY_DSN=${SENTRY_DSN}
      
      # Redis (optional)
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
      # OAuth2 (optional)
      - OAUTH2_ENABLED=${OAUTH2_ENABLED:-false}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      
      # CORS
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      
    volumes:
      - /home/ec2-user/autocoin-logs:/app/logs
      - /home/ec2-user/autocoin-temp:/app/temp
    networks:
      - autocoin-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ====================================
  # Redis Cache (Optional)
  # ====================================
  redis:
    image: redis:7-alpine
    container_name: autocoin-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - autocoin-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - redis

volumes:
  redis-data:
    driver: local

networks:
  autocoin-network:
    driver: bridge
