# ====================================
# Dev Environment Configuration
# ====================================
# 개발/테스트 서버 환경 전용 설정

spring:
  # 데이터소스 설정 (AWS RDS)
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    
    # HikariCP 설정 (개발서버 최적화)
    hikari:
      pool-name: AutocoinHikariCP-Dev
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 30000


  # Redis 설정 (로컬 Docker)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-wait: -1ms
          max-idle: 8
          min-idle: 2

  # JPA/Hibernate 설정 (검증 모드)
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: ${HIBERNATE_BATCH_SIZE:50}

  # 개발 도구 비활성화
  devtools:
    restart:
      enabled: false

# 로깅 설정 (개발서버용)
logging:
  level:
    com.autocoin: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
  file:
    name: ${LOG_FILE_NAME:logs/autocoin-dev.log}

# 모니터링 설정 (개발서버용)
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: when-authorized

# Swagger 활성화 (개발서버용)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# CORS 설정 (개발서버용)
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://dev.autocoin.com,http://localhost:3000}
