version: '3.8'

services:
  # ====================================
  # Autocoin Spring API
  # ====================================
  autocoin-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: autocoin-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - autocoin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - redis

  # ====================================
  # Redis
  # ====================================
  redis:
    image: redis:7.0-alpine
    container_name: autocoin-redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - autocoin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis-data:
    driver: local

networks:
  autocoin-network:
    driver: bridge
