apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "autocoin-logs-*"
    interval: Daily
    timeField: "@timestamp"
    version: 80
    editable: false
    jsonData:
      esVersion: 80
      interval: Daily
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
      includeFrozen: false
